export const chatCopy = {
  title: "问答",
  description: "在授权知识库范围内提问，并核验答案引用来源。",
  sessionsDescription: "切换历史会话，或在当前知识库中新建问答上下文。",
  newSession: "新建会话",
  composerLabel: "输入问题",
  composerPlaceholder: "例如：差旅住宿标准是多少？",
  submitQuestion: "发送问题",
  citationPanel: "引用核验",
  noCitation: "当前答案没有可支撑的引用来源，请谨慎使用。",
  failed: "回答生成失败，请重试。",
  retryFailed: "重试失败答案",
  submittedHint: "已保存本次反馈。",
  feedbackUseful: "有帮助",
  feedbackNotUseful: "无帮助",
  feedbackReason: "反馈原因",
  feedbackDisabled: "该答案已提交反馈。",
  submitDisabled: "请输入问题后发送。",
  submitFeedback: "提交反馈",
  feedbackSubmitted: "反馈已提交",
  modes: {
    with_citation: "生成带引用答案",
    retrieving: "仅展示检索中状态",
    generating: "仅展示生成中状态",
    no_citation: "生成无引用答案",
    failed: "生成失败状态",
  },
} as const;
