export const knowledgeCopy = {
  workspaceTitle: "知识库工作台",
  workspaceDescription: "集中管理知识库成员、文档接入准备状态与知识库基础信息。",
  listTitle: "知识库列表",
  listDescription: "搜索状态会写入当前 URL。",
  listScrollHint: "继续向下滑动加载更多知识库。",
  searchLabel: "搜索知识库",
  searchPlaceholder: "按名称或描述搜索",
  retry: "重试",
  createKnowledgeBase: "新建知识库",
  createKnowledgeBaseDescription: "填写名称、描述和成员后保存知识库。",
  editKnowledgeBase: "编辑知识库",
  editKnowledgeBaseDescription: "修改名称、描述和成员分配。",
  save: "保存",
  cancel: "取消",
  openChat: "进入问答",
  uploadFile: "上传文件",
  uploadFileDescription: "选择 PDF、Markdown 或 TXT 文件，提交后会创建文档和处理任务。",
  uploadFileHelp: "支持 PDF、Markdown、TXT，单个文件不超过 8 MB。",
  uploadFileLabel: "文件",
  uploadTitleLabel: "文档标题（可选）",
  uploadTitlePlaceholder: "留空时使用文件名",
  importUrl: "导入网页",
  importUrlDescription: "粘贴 URL 后创建抓取和切分任务。",
  labels: {
    createdAt: "创建时间",
    description: "描述",
    documentCount: "文档数",
    documentCountValue: (count: number) => `${count} 个文档`,
    memberCount: "成员数",
    memberCountValue: (count: number) => `${count} 名成员`,
    name: "知识库名称",
    noDescription: "暂无描述",
  },
  members: {
    description: "可按成员姓名或邮箱搜索，未分配成员也可以保存。",
    empty: "未分配成员，默认仅管理员可见。",
    searchLabel: "成员",
    searchPlaceholder: "搜索成员姓名或邮箱",
    selectionLabel: "已选成员",
  },
  validation: {
    emptyFile: "上传文件不能为空。",
    nameRequired: "请输入知识库名称。",
    fileRequired: "请选择一个文件。",
    fileTooLarge: "文件超过大小限制，请选择 8 MB 以内的文件。",
    singleFileOnly: "每次只能上传一个文件。",
    unsupportedUploadFileType: "仅支持上传 PDF、Markdown 或 TXT 文件。",
    uploadTitleTooLong: "文档标题不能超过 500 个字符。",
    urlRequired: "请输入有效网页地址。",
  },
  pending: {
    knowledgeBaseDetail: "正在加载知识库详情。",
    knowledgeBaseList: "正在加载知识库列表。",
    memberList: "正在加载成员列表。",
    moreKnowledgeBases: "正在加载更多知识库。",
    savingKnowledgeBase: "正在保存知识库。",
    uploadingFile: "正在上传文件。",
  },
  empty: {
    knowledgeBaseList: "当前租户下还没有知识库。",
    noKnowledgeBaseSelected: "暂无可查看的知识库，请先新建知识库。",
    searchResult: "当前搜索条件下没有匹配的知识库。",
  },
  errors: {
    duplicateKnowledgeBase: "当前租户下已存在同名知识库。",
    knowledgeBaseDetail: "知识库详情加载失败，请稍后重试。",
    knowledgeBaseList: "知识库列表加载失败，请稍后重试。",
    memberList: "成员列表加载失败，请稍后重试。",
    saveKnowledgeBase: "知识库保存失败，请稍后重试。",
  },
  success: {
    created: "知识库已创建。",
    updated: "知识库已更新。",
  },
  uploadSuccess: {
    duplicate: (title: string) => `相同内容已存在，已使用文档「${title}」。`,
    queued: (title: string) => `文档「${title}」已上传，处理任务已排队。`,
    uploaded: (title: string) => `文档「${title}」已上传。`,
  },
  uploadErrors: {
    conflict: "上传内容存在冲突，请刷新后重试。",
    forbidden: "你没有权限向该知识库上传文件。",
    generic: "文件上传失败，请稍后重试。",
    notFound: "知识库不存在或已被删除。",
    payloadTooLarge: "文件超过大小限制，请选择 8 MB 以内的文件。",
    rateLimited: "上传请求过于频繁，请稍后重试。",
    unauthorized: "登录状态已失效，请重新登录后再上传。",
    unsupportedMediaType: "仅支持上传 PDF、Markdown 或 TXT 文件。",
    validation: "请检查文件和标题后重试。",
  },
  disabled: {
    createKnowledgeBase: "只有 admin 用户可以新建知识库，避免重复创建。",
    importPending: "网页导入将在接入真实文档 API 后开放。",
    importUrl: "请先选择或创建知识库。",
    upload: "请先选择或创建知识库。",
    uploadPending: "文件上传将在接入真实文档 API 后开放。",
  },
} as const;
