export const knowledgeCopy = {
  workspaceTitle: "知识库工作台",
  workspaceDescription: "集中管理知识库、文档导入、任务状态和处理日志。",
  createKnowledgeBase: "新建知识库",
  createKnowledgeBaseDescription: "创建后会立即出现在左侧知识库列表中。",
  uploadFile: "上传文件",
  uploadFileDescription: "提交后会创建文档、任务和处理日志。",
  importUrl: "导入网页",
  importUrlDescription: "粘贴 URL 后创建抓取和切分任务。",
  documentsTitle: "文档",
  documentListTitle: "文档列表",
  documentDetailTitle: "文档详情",
  sourcePreview: "来源预览",
  chunks: "片段",
  recentTasks: "近期任务",
  recentLogs: "近期处理日志",
  noChunks: "该文档暂未生成片段，请查看任务或处理日志。",
  chunkDrawerTitle: "片段详情",
  validation: {
    nameRequired: "请输入知识库名称。",
    fileRequired: "请输入文件名。",
    urlRequired: "请输入有效网页地址。",
  },
  disabled: {
    createKnowledgeBase: "只有 admin 用户可以新建知识库，避免重复创建。",
    upload: "请先选择或创建知识库。",
    importUrl: "请先选择或创建知识库。",
    readyDocumentRetry: "可用文档不需要重试。",
  },
} as const;
