CREATE UNIQUE INDEX "document_chunks_tenant_id_id_idx" ON "document_chunks" USING btree ("tenant_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "documents_tenant_id_id_idx" ON "documents" USING btree ("tenant_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "knowledge_bases_tenant_id_id_idx" ON "knowledge_bases" USING btree ("tenant_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "provider_configs_tenant_id_id_idx" ON "provider_configs" USING btree ("tenant_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "secret_records_tenant_id_id_idx" ON "secret_records" USING btree ("tenant_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "answer_feedback_tenant_id_id_idx" ON "answer_feedback" USING btree ("tenant_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "chat_messages_tenant_id_id_idx" ON "chat_messages" USING btree ("tenant_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "chat_sessions_tenant_id_id_idx" ON "chat_sessions" USING btree ("tenant_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX "retrieval_runs_tenant_id_id_idx" ON "retrieval_runs" USING btree ("tenant_id","id");--> statement-breakpoint
ALTER TABLE "ingestion_jobs" ADD CONSTRAINT "ingestion_jobs_tenant_kb_fk" FOREIGN KEY ("tenant_id","knowledge_base_id") REFERENCES "public"."knowledge_bases"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ingestion_jobs" ADD CONSTRAINT "ingestion_jobs_tenant_document_fk" FOREIGN KEY ("tenant_id","document_id") REFERENCES "public"."documents"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chunk_embeddings" ADD CONSTRAINT "chunk_embeddings_tenant_kb_fk" FOREIGN KEY ("tenant_id","knowledge_base_id") REFERENCES "public"."knowledge_bases"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chunk_embeddings" ADD CONSTRAINT "chunk_embeddings_tenant_document_fk" FOREIGN KEY ("tenant_id","document_id") REFERENCES "public"."documents"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chunk_embeddings" ADD CONSTRAINT "chunk_embeddings_tenant_chunk_fk" FOREIGN KEY ("tenant_id","chunk_id") REFERENCES "public"."document_chunks"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_chunks" ADD CONSTRAINT "document_chunks_tenant_kb_fk" FOREIGN KEY ("tenant_id","knowledge_base_id") REFERENCES "public"."knowledge_bases"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_chunks" ADD CONSTRAINT "document_chunks_tenant_document_fk" FOREIGN KEY ("tenant_id","document_id") REFERENCES "public"."documents"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_sources" ADD CONSTRAINT "document_sources_tenant_kb_fk" FOREIGN KEY ("tenant_id","knowledge_base_id") REFERENCES "public"."knowledge_bases"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document_sources" ADD CONSTRAINT "document_sources_tenant_document_fk" FOREIGN KEY ("tenant_id","document_id") REFERENCES "public"."documents"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documents" ADD CONSTRAINT "documents_tenant_kb_fk" FOREIGN KEY ("tenant_id","knowledge_base_id") REFERENCES "public"."knowledge_bases"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "knowledge_base_members" ADD CONSTRAINT "knowledge_base_members_tenant_kb_fk" FOREIGN KEY ("tenant_id","knowledge_base_id") REFERENCES "public"."knowledge_bases"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provider_configs" ADD CONSTRAINT "provider_configs_tenant_secret_fk" FOREIGN KEY ("tenant_id","secret_record_id") REFERENCES "public"."secret_records"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "answer_citations" ADD CONSTRAINT "answer_citations_tenant_message_fk" FOREIGN KEY ("tenant_id","message_id") REFERENCES "public"."chat_messages"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "answer_citations" ADD CONSTRAINT "answer_citations_tenant_run_fk" FOREIGN KEY ("tenant_id","retrieval_run_id") REFERENCES "public"."retrieval_runs"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "answer_citations" ADD CONSTRAINT "answer_citations_tenant_kb_fk" FOREIGN KEY ("tenant_id","knowledge_base_id") REFERENCES "public"."knowledge_bases"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "answer_citations" ADD CONSTRAINT "answer_citations_tenant_document_fk" FOREIGN KEY ("tenant_id","document_id") REFERENCES "public"."documents"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "answer_citations" ADD CONSTRAINT "answer_citations_tenant_chunk_fk" FOREIGN KEY ("tenant_id","chunk_id") REFERENCES "public"."document_chunks"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "answer_feedback" ADD CONSTRAINT "answer_feedback_tenant_message_fk" FOREIGN KEY ("tenant_id","message_id") REFERENCES "public"."chat_messages"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "answer_feedback" ADD CONSTRAINT "answer_feedback_tenant_run_fk" FOREIGN KEY ("tenant_id","retrieval_run_id") REFERENCES "public"."retrieval_runs"("tenant_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "answer_feedback_citations" ADD CONSTRAINT "answer_feedback_citations_tenant_feedback_fk" FOREIGN KEY ("tenant_id","feedback_id") REFERENCES "public"."answer_feedback"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_tenant_session_fk" FOREIGN KEY ("tenant_id","session_id") REFERENCES "public"."chat_sessions"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "retrieval_results" ADD CONSTRAINT "retrieval_results_tenant_run_fk" FOREIGN KEY ("tenant_id","run_id") REFERENCES "public"."retrieval_runs"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "retrieval_results" ADD CONSTRAINT "retrieval_results_tenant_kb_fk" FOREIGN KEY ("tenant_id","knowledge_base_id") REFERENCES "public"."knowledge_bases"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "retrieval_results" ADD CONSTRAINT "retrieval_results_tenant_document_fk" FOREIGN KEY ("tenant_id","document_id") REFERENCES "public"."documents"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "retrieval_results" ADD CONSTRAINT "retrieval_results_tenant_chunk_fk" FOREIGN KEY ("tenant_id","chunk_id") REFERENCES "public"."document_chunks"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "retrieval_runs" ADD CONSTRAINT "retrieval_runs_tenant_session_fk" FOREIGN KEY ("tenant_id","session_id") REFERENCES "public"."chat_sessions"("tenant_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "retrieval_runs" ADD CONSTRAINT "retrieval_runs_tenant_message_fk" FOREIGN KEY ("tenant_id","message_id") REFERENCES "public"."chat_messages"("tenant_id","id") ON DELETE no action ON UPDATE no action;
